from src.departments.base import BaseDepartment, BaseWorker
from src.core.models import Task, TaskStatus

class CodingWorker(BaseWorker):
    def execute(self, task: Task) -> Task:
        query = task.input_data.get("request", task.input_data.get("objective", ""))
        print(f"[CodingWorker] Processing coding task: {query[:80]}...")
        
        if not self.engine:
            # Enhanced simulation for coding tasks
            lower_query = query.lower()
            if any(word in lower_query for word in ["write", "code", "function", "class", "python", "rust"]):
                response = """```python
# Example code generated by JARVIS Coding Specialist

def example_function(data):
    \"\"\"Example function with proper documentation.\"\"\"
    result = []
    for item in data:
        if isinstance(item, (int, float)):
            result.append(item * 2)
    return result

# Usage:
# data = [1, 2, 3, 4]
# print(example_function(data))
```"""
            else:
                response = "Please provide a specific coding task (e.g. 'Write a Python function to...')."
        else:
            prompt = f"""You are JARVIS Coding Specialist — an expert software engineer.
You specialize in clean, efficient, and well-documented code.

Task: {query}

Provide the solution with explanation:"""
            response = self.engine.generate(prompt)
        
        task.output_data = {
            "code": response,
            "language": "python",
            "explanation": "Generated by JARVIS Coding Department"
        }
        task.status = TaskStatus.COMPLETED
        task.progress = 1.0
        return task

class CodingDepartment(BaseDepartment):
    def __init__(self, engine=None):
        super().__init__("Coding")
        self.engine = engine

    def initialize(self, event_bus):
        super().initialize(event_bus)
        self.manager.register_worker(CodingWorker("coding-worker-01", self.engine))
