import logging
import traceback
from src.departments.base import BaseDepartment, BaseWorker
from src.core.models import Task, TaskStatus

logger = logging.getLogger(__name__)


class CodingWorker(BaseWorker):
    def __init__(self, worker_id: str, engine=None, secure_memory=None, secure_runner=None):
        super().__init__(worker_id)
        self.engine = engine
        self.secure_memory = secure_memory
        self.secure_runner = secure_runner
        logger.info(f"[{worker_id}] Initialized with secure_memory={secure_memory is not None}")

    def execute(self, task: Task) -> Task:
        query = task.input_data.get("request") or task.input_data.get("objective", "")
        logger.info(f"[CodingWorker] Processing: {query[:80]}...")

        try:
            if self.engine is None or self.engine.llm is None:
                lower_query = query.lower()
                if any(word in lower_query for word in ["write", "code", "function", "class", "python", "rust"]):
                    response = """```python
# Example code generated by JARVIS Coding Specialist

def example_function(data):
    \"\"\"Example function with proper documentation.\"\"\"
    result = []
    for item in data:
        if isinstance(item, (int, float)):
            result.append(item * 2)
    return result
```"""
                else:
                    response = "Please provide a specific coding task (e.g. 'Write a Python function to...')."
            else:
                prompt = f"""You are JARVIS Coding Specialist — an expert software engineer.
You specialize in clean, efficient, and well-documented code.

Task: {query}

Provide the solution with explanation:"""
                response = self.engine.generate(prompt, max_tokens=1024, temperature=0.3)

            task.output_data = {
                "code": response,
                "language": "python",
                "explanation": "Generated by JARVIS Coding Department"
            }
            task.status = TaskStatus.COMPLETED
            task.progress = 1.0
        except Exception as e:
            logger.error(f"[CodingWorker] Error: {e}", exc_info=True)
            task.status = TaskStatus.FAILED
            task.output_data = {"error": str(e)}

        return task


class CodingDepartment(BaseDepartment):
    def __init__(self, engine=None, secure_memory=None, secure_runner=None):
        super().__init__("Coding")
        self.engine = engine
        self.secure_memory = secure_memory
        self.secure_runner = secure_runner

    def initialize(self, event_bus):
        super().initialize(event_bus)
        worker = CodingWorker(
            "coding-worker-01",
            engine=self.engine,
            secure_memory=self.secure_memory,
            secure_runner=self.secure_runner,
        )
        self.manager.register_worker(worker)
        logger.info("[Coding] Department initialized and worker registered.")
