import logging
import traceback
from typing import Optional, Any, Dict

# Secure components (will be injected)
try:
    from memory.secure_store import SecureMemoryStore
except ImportError:
    SecureMemoryStore = None

try:
    from core.secure_runner import SecureCommandRunner
except ImportError:
    SecureCommandRunner = None

# Your existing base imports
from src.departments.base import BaseDepartment, BaseWorker
from src.core.models import Task, TaskStatus

# Logger for this module
logger = logging.getLogger(__name__)


class CodingWorker(BaseWorker):
    """
    Worker that handles coding tasks.
    Secured with optional memory storage and command execution.
    """

    def __init__(
        self,
        worker_id: str,
        engine=None,
        secure_memory: Optional[SecureMemoryStore] = None,
        secure_runner: Optional[SecureCommandRunner] = None,
    ):
        super().__init__(worker_id)
        self.engine = engine
        self.secure_memory = secure_memory
        self.secure_runner = secure_runner
        logger.info(f"[{worker_id}] Initialized with secure_memory={secure_memory is not None}")

    def _get_query(self, task: Task) -> str:
        """Safely extract the coding query from task input."""
        query = task.input_data.get("request") or task.input_data.get("objective")
        if not query:
            query = task.input_data.get("text", "")  # fallback
        return str(query).strip()

    def _save_to_memory(self, query: str, response: str, metadata: Dict[str, Any]) -> None:
        """Store the interaction in the secure memory database (if available)."""
        if self.secure_memory is None:
            return
        try:
            self.secure_memory.insert(
                text=f"CODING: {query}",
                metadata={
                    "type": "coding_interaction",
                    "response_preview": response[:200],
                    **metadata,
                },
            )
            logger.debug(f"[{self.worker_id}] Stored coding interaction in memory.")
        except Exception as e:
            logger.warning(f"[{self.worker_id}] Failed to store in memory: {e}")

    def execute(self, task: Task) -> Task:
        query = self._get_query(task)
        if not query:
            task.status = TaskStatus.FAILED
            task.output_data = {"error": "No coding request or objective provided."}
            logger.warning(f"[{self.worker_id}] Task rejected: empty query.")
            return task

        logger.info(f"[{self.worker_id}] Processing coding task: {query[:80]}...")

        try:
            # ---------- 1. SIMULATION MODE (fallback) ----------
            if self.engine is None or self.engine.llm is None:
                logger.info(f"[{self.worker_id}] Using simulation mode.")
                lower_query = query.lower()

                if any(word in lower_query for word in ["write", "code", "function", "class", "python", "rust"]):
                    response = """```python
# Example code generated by JARVIS Coding Specialist

def example_function(data):
    \"\"\"Example function with proper documentation.\"\"\"
    result = []
    for item in data:
        if isinstance(item, (int, float)):
            result.append(item * 2)
    return result

# Usage:
# data = [1, 2, 3, 4]
# print(example_function(data))
```"""
                else:
                    response = "Please provide a specific coding task (e.g. 'Write a Python function to...')."

            # ---------- 2. REAL LLM MODE ----------
            else:
                logger.info(f"[{self.worker_id}] Generating code via LLM.")
                prompt = f"""You are JARVIS Coding Specialist — an expert software engineer.
You specialize in clean, efficient, and well-documented code.

Task: {query}

Provide the solution with explanation:"""

                response = self.engine.generate(
                    prompt,
                    max_tokens=1024,      # Code generation needs more tokens
                    temperature=0.3,      # Lower temp for deterministic code
                    stream=False,
                )

                # If the response is an error string from the engine, treat it as failure
                if response.startswith("[ERROR]") or "failed" in response.lower():
                    raise RuntimeError(f"LLM engine returned an error: {response}")

            # ---------- 3. STORE IN SECURE MEMORY ----------
            self._save_to_memory(
                query=query,
                response=response,
                metadata={"worker_id": self.worker_id, "language": "python"},
            )

            # ---------- 4. SET TASK OUTPUT ----------
            task.output_data = {
                "code": response,
                "language": "python",
                "explanation": "Generated by JARVIS Coding Department",
                "raw_response": response,  # for debugging
            }
            task.status = TaskStatus.COMPLETED
            task.progress = 1.0

        except Exception as e:
            error_trace = traceback.format_exc()
            logger.error(f"[{self.worker_id}] Task failed: {e}\n{error_trace}")
            task.status = TaskStatus.FAILED
            task.output_data = {
                "error": str(e),
                "trace": error_trace,
                "code": "// Error generating code. Check logs.",
            }
            task.progress = 0.0

        return task


class CodingDepartment(BaseDepartment):
    """
    Department responsible for code generation and analysis.
    Accepts secure components via setters for dependency injection.
    """

    def __init__(self, engine=None):
        super().__init__("Coding")
        self.engine = engine
        self._secure_memory: Optional[SecureMemoryStore] = None
        self._secure_runner: Optional[SecureCommandRunner] = None
        self._worker: Optional[CodingWorker] = None

    def set_secure_memory(self, secure_memory: SecureMemoryStore):
        """Dependency injection for secure memory (called by main.py)."""
        self._secure_memory = secure_memory
        # If worker already exists, update it
        if self._worker:
            self._worker.secure_memory = secure_memory
        logger.info(f"[{self.name}] SecureMemoryStore attached.")

    def set_secure_runner(self, secure_runner: SecureCommandRunner):
        """Dependency injection for secure command runner (called by main.py)."""
        self._secure_runner = secure_runner
        if self._worker:
            self._worker.secure_runner = secure_runner
        logger.info(f"[{self.name}] SecureCommandRunner attached.")

    def initialize(self, event_bus):
        super().initialize(event_bus)

        # Create the worker with the engine and any injected secure components
        self._worker = CodingWorker(
            worker_id=f"{self.name.lower()}-worker-01",
            engine=self.engine,
            secure_memory=self._secure_memory,
            secure_runner=self._secure_runner,
        )
        self.manager.register_worker(self._worker)
        logger.info(f"[{self.name}] Department initialized and worker registered.")

    # Optional: If your BaseDepartment expects a shutdown method
    def shutdown(self):
        """Clean up resources if needed."""
        logger.info(f"[{self.name}] Shutting down.")
        self._worker = None
