from typing import Any, Dict, List, Protocol, runtime_checkable
from .models import Task, Event

@runtime_checkable
class IEventBus(Protocol):
    def publish(self, event: Event) -> None: ...
    def subscribe(self, event_type: str, callback: Any) -> None: ...

@runtime_checkable
class IWorker(Protocol):
    def execute(self, task: Task) -> Task: ...
    def get_profile(self) -> Dict[str, Any]: ...

@runtime_checkable
class IDepartmentManager(Protocol):
    def handle_task(self, task: Task) -> None: ...
    def register_worker(self, worker: IWorker) -> None: ...

@runtime_checkable
class IDepartment(Protocol):
    @property
    def name(self) -> str: ...
    def initialize(self, event_bus: IEventBus) -> None: ...

@runtime_checkable
class IChiefOfStaff(Protocol):
    def schedule_task(self, task: Task) -> None: ...
    def monitor_progress(self) -> Dict[str, Any]: ...

@runtime_checkable
class ICEO(Protocol):
    def process_request(self, user_input: str) -> str: ...
